local M = {}
M.opts = {
	default_remote = { "upstream", "origin" }, -- order to try remotes
	reaction_viewer_hint_icon = "", -- marker for user reactions
	user_icon = " ", -- user icon
	timeline_marker = "", -- timeline marker
	timeline_indent = "2", -- timeline indentation
	right_bubble_delimiter = "", -- Bubble delimiter
	left_bubble_delimiter = "", -- Bubble delimiter
	github_hostname = "", -- GitHub Enterprise host
	snippet_context_lines = 4, -- number or lines around commented lines
	file_panel = {
		size = 10, -- changed files panel rows
		use_icons = true,                       -- use web-devicons in file panel
	},
	mappings = {
		issue = {
			close_issue = "<space>O<space>ic", -- close issue
			reopen_issue = "<space>O<space>io", -- reopen issue
			list_issues = "<space>O<space>il", -- list open issues on same repo
			reload = "<space>O<C-r>", -- reload issue
			open_in_browser = "<space>O<C-b>", -- open issue in browser
			copy_url = "<space>O<C-y>", -- copy url to system clipboard
			add_assignee = "<space>O<space>aa", -- add assignee
			remove_assignee = "<space>O<space>ad", -- remove assignee
			create_label = "<space>O<space>lc", -- create label
			add_label = "<space>O<space>la", -- add label
			remove_label = "<space>O<space>ld", -- remove label
			goto_issue = "<space>O<space>gi", -- navigate to a local repo issue
			add_comment = "<space>O<space>ca", -- add comment
			delete_comment = "<space>O<space>cd", -- delete comment
			next_comment = "<space>O]c", -- go to next comment
			prev_comment = "<space>O[c", -- go to previous comment
			react_hooray = "<space>O<space>rp", -- add/remove 🎉 reaction
			react_heart = "<space>O<space>rh", -- add/remove ❤️ reaction
			react_eyes = "<space>O<space>re", -- add/remove 👀 reaction
			react_thumbs_up = "<space>O<space>r+", -- add/remove 👍 reaction
			react_thumbs_down = "<space>O<space>r-", -- add/remove 👎 reaction
			react_rocket = "<space>O<space>rr", -- add/remove 🚀 reaction
			react_laugh = "<space>O<space>rl", -- add/remove 😄 reaction
			react_confused = "<space>O<space>rc", -- add/remove 😕 reaction
		},
		pull_request = {
			checkout_pr = "<space>O<space>po", -- checkout PR
			merge_pr = "<space>O<space>pm", -- merge PR
			list_commits = "<space>O<space>pc", -- list PR commits
			list_changed_files = "<space>O<space>pf", -- list PR changed files
			show_pr_diff = "<space>O<space>pd", -- show PR diff
			add_reviewer = "<space>O<space>va", -- add reviewer
			remove_reviewer = "<space>O<space>vd", -- remove reviewer request
			close_issue = "<space>O<space>ic", -- close PR
			reopen_issue = "<space>O<space>io", -- reopen PR
			list_issues = "<space>O<space>il", -- list open issues on same repo
			reload = "<space>O<C-r>", -- reload PR
			open_in_browser = "<space>O<C-b>", -- open PR in browser
			copy_url = "<space>O<C-y>", -- copy url to system clipboard
			add_assignee = "<space>O<space>aa", -- add assignee
			remove_assignee = "<space>O<space>ad", -- remove assignee
			create_label = "<space>O<space>lc", -- create label
			add_label = "<space>O<space>la", -- add label
			remove_label = "<space>O<space>ld", -- remove label
			goto_issue = "<space>O<space>gi", -- navigate to a local repo issue
			add_comment = "<space>O<space>ca", -- add comment
			delete_comment = "<space>O<space>cd", -- delete comment
			next_comment = "<space>O]c", -- go to next comment
			prev_comment = "<space>O[c", -- go to previous comment
			react_hooray = "<space>O<space>rp", -- add/remove 🎉 reaction
			react_heart = "<space>O<space>rh", -- add/remove ❤️ reaction
			react_eyes = "<space>O<space>re", -- add/remove 👀 reaction
			react_thumbs_up = "<space>O<space>r+", -- add/remove 👍 reaction
			react_thumbs_down = "<space>O<space>r-", -- add/remove 👎 reaction
			react_rocket = "<space>O<space>rr", -- add/remove 🚀 reaction
			react_laugh = "<space>O<space>rl", -- add/remove 😄 reaction
			react_confused = "<space>O<space>rc", -- add/remove 😕 reaction
		},
		review_thread = {
			goto_issue = "<space>O<space>gi", -- navigate to a local repo issue
			add_comment = "<space>O<space>ca", -- add comment
			add_suggestion = "<space>O<space>sa", -- add suggestion
			delete_comment = "<space>O<space>cd", -- delete comment
			next_comment = "<space>O]c", -- go to next comment
			prev_comment = "<space>O[c", -- go to previous comment
			select_next_entry = "<space>O]q", -- move to previous changed file
			select_prev_entry = "<space>O[q", -- move to next changed file
			close_review_tab = "<space>O<C-c>", -- close review tab
			react_hooray = "<space>O<space>rp", -- add/remove 🎉 reaction
			react_heart = "<space>O<space>rh", -- add/remove ❤️ reaction
			react_eyes = "<space>O<space>re", -- add/remove 👀 reaction
			react_thumbs_up = "<space>O<space>r+", -- add/remove 👍 reaction
			react_thumbs_down = "<space>O<space>r-", -- add/remove 👎 reaction
			react_rocket = "<space>O<space>rr", -- add/remove 🚀 reaction
			react_laugh = "<space>O<space>rl", -- add/remove 😄 reaction
			react_confused = "<space>O<space>rc", -- add/remove 😕 reaction
		},
		submit_win = {
			approve_review = "<space>O<C-a>", -- approve review
			comment_review = "<space>O<C-m>", -- comment review
			request_changes = "<space>O<C-r>", -- request changes review
			close_review_tab = "<space>O<C-c>", -- close review tab
		},
		review_diff = {
			add_review_comment = "<space>O<space>ca", -- add a new review comment
			add_review_suggestion = "<space>O<space>sa", -- add a new review suggestion
			focus_files = "<space>O<leader>e", -- move focus to changed file panel
			toggle_files = "<space>O<leader>b", -- hide/show changed files panel
			next_thread = "<space>O]t", -- move to next thread
			prev_thread = "<space>O[t", -- move to previous thread
			select_next_entry = "<space>O]q", -- move to previous changed file
			select_prev_entry = "<space>O[q", -- move to next changed file
			close_review_tab = "<space>O<C-c>", -- close review tab
			toggle_viewed = "<space>O<leader><space>", -- toggle viewer viewed state
		},
		file_panel = {
			next_entry = "<space>Oj", -- move to next changed file
			prev_entry = "<space>Ok", -- move to previous changed file
			select_entry = "<space>O<cr>", -- show selected changed file diffs
			refresh_files = "<space>OR", -- refresh changed files panel
			focus_files = "<space>O<leader>e", -- move focus to changed file panel
			toggle_files = "<space>O<leader>b", -- hide/show changed files panel
			select_next_entry = "<space>O]q", -- move to previous changed file
			select_prev_entry = "<space>O[q", -- move to next changed file
			close_review_tab = "<space>O<C-c>", -- close review tab
			toggle_viewed = "<space>O<leader><space>", -- toggle viewer viewed state
		},
	},
}

M.setup = function()
	require("octo").setup({
		default_remote = { "upstream", "origin" }, -- order to try remotes
		reaction_viewer_hint_icon = "", -- marker for user reactions
		user_icon = " ", -- user icon
		timeline_marker = "", -- timeline marker
		timeline_indent = "2", -- timeline indentation
		right_bubble_delimiter = "", -- Bubble delimiter
		left_bubble_delimiter = "", -- Bubble delimiter
		github_hostname = "", -- GitHub Enterprise host
		snippet_context_lines = 4, -- number or lines around commented lines
		file_panel = {
			size = 10, -- changed files panel rows
			use_icons = true,                       -- use web-devicons in file panel
		},
		mappings = {
			issue = {
				close_issue = "Z<space>ic", -- close issue
				reopen_issue = "Z<space>io", -- reopen issue
				list_issues = "Z<space>il", -- list open issues on same repo
				reload = "Z<C-r>", -- reload issue
				open_in_browser = "Z<C-b>", -- open issue in browser
				copy_url = "Z<C-y>", -- copy url to system clipboard
				add_assignee = "Z<space>aa", -- add assignee
				remove_assignee = "Z<space>ad", -- remove assignee
				create_label = "Z<space>lc", -- create label
				add_label = "Z<space>la", -- add label
				remove_label = "Z<space>ld", -- remove label
				goto_issue = "Z<space>gi", -- navigate to a local repo issue
				add_comment = "Z<space>ca", -- add comment
				delete_comment = "Z<space>cd", -- delete comment
				next_comment = "Z]c", -- go to next comment
				prev_comment = "Z[c", -- go to previous comment
				react_hooray = "Z<space>rp", -- add/remove 🎉 reaction
				react_heart = "Z<space>rh", -- add/remove ❤️ reaction
				react_eyes = "Z<space>re", -- add/remove 👀 reaction
				react_thumbs_up = "Z<space>r+", -- add/remove 👍 reaction
				react_thumbs_down = "Z<space>r-", -- add/remove 👎 reaction
				react_rocket = "Z<space>rr", -- add/remove 🚀 reaction
				react_laugh = "Z<space>rl", -- add/remove 😄 reaction
				react_confused = "Z<space>rc", -- add/remove 😕 reaction
			},
			pull_request = {
				checkout_pr = "Z<space>po", -- checkout PR
				merge_pr = "Z<space>pm", -- merge PR
				list_commits = "Z<space>pc", -- list PR commits
				list_changed_files = "Z<space>pf", -- list PR changed files
				show_pr_diff = "Z<space>pd", -- show PR diff
				add_reviewer = "Z<space>va", -- add reviewer
				remove_reviewer = "Z<space>vd", -- remove reviewer request
				close_issue = "Z<space>ic", -- close PR
				reopen_issue = "Z<space>io", -- reopen PR
				list_issues = "Z<space>il", -- list open issues on same repo
				reload = "Z<C-r>", -- reload PR
				open_in_browser = "Z<C-b>", -- open PR in browser
				copy_url = "Z<C-y>", -- copy url to system clipboard
				add_assignee = "Z<space>aa", -- add assignee
				remove_assignee = "Z<space>ad", -- remove assignee
				create_label = "Z<space>lc", -- create label
				add_label = "Z<space>la", -- add label
				remove_label = "Z<space>ld", -- remove label
				goto_issue = "Z<space>gi", -- navigate to a local repo issue
				add_comment = "Z<space>ca", -- add comment
				delete_comment = "Z<space>cd", -- delete comment
				next_comment = "Z]c", -- go to next comment
				prev_comment = "Z[c", -- go to previous comment
				react_hooray = "Z<space>rp", -- add/remove 🎉 reaction
				react_heart = "Z<space>rh", -- add/remove ❤️ reaction
				react_eyes = "Z<space>re", -- add/remove 👀 reaction
				react_thumbs_up = "Z<space>r+", -- add/remove 👍 reaction
				react_thumbs_down = "Z<space>r-", -- add/remove 👎 reaction
				react_rocket = "Z<space>rr", -- add/remove 🚀 reaction
				react_laugh = "Z<space>rl", -- add/remove 😄 reaction
				react_confused = "Z<space>rc", -- add/remove 😕 reaction
			},
			review_thread = {
				goto_issue = "Z<space>gi", -- navigate to a local repo issue
				add_comment = "Z<space>ca", -- add comment
				add_suggestion = "Z<space>sa", -- add suggestion
				delete_comment = "Z<space>cd", -- delete comment
				next_comment = "Z]c", -- go to next comment
				prev_comment = "Z[c", -- go to previous comment
				select_next_entry = "Z]q", -- move to previous changed file
				select_prev_entry = "Z[q", -- move to next changed file
				close_review_tab = "Z<C-c>", -- close review tab
				react_hooray = "Z<space>rp", -- add/remove 🎉 reaction
				react_heart = "Z<space>rh", -- add/remove ❤️ reaction
				react_eyes = "Z<space>re", -- add/remove 👀 reaction
				react_thumbs_up = "Z<space>r+", -- add/remove 👍 reaction
				react_thumbs_down = "Z<space>r-", -- add/remove 👎 reaction
				react_rocket = "Z<space>rr", -- add/remove 🚀 reaction
				react_laugh = "Z<space>rl", -- add/remove 😄 reaction
				react_confused = "Z<space>rc", -- add/remove 😕 reaction
			},
			submit_win = {
				approve_review = "Z<C-a>", -- approve review
				comment_review = "Z<C-m>", -- comment review
				request_changes = "Z<C-r>", -- request changes review
				close_review_tab = "Z<C-c>", -- close review tab
			},
			review_diff = {
				add_review_comment = "Z<space>ca", -- add a new review comment
				add_review_suggestion = "Z<space>sa", -- add a new review suggestion
				focus_files = "Z<leader>e", -- move focus to changed file panel
				toggle_files = "Z<leader>b", -- hide/show changed files panel
				next_thread = "Z]t", -- move to next thread
				prev_thread = "Z[t", -- move to previous thread
				select_next_entry = "Z]q", -- move to previous changed file
				select_prev_entry = "Z[q", -- move to next changed file
				close_review_tab = "Z<C-c>", -- close review tab
				toggle_viewed = "Z<leader><space>", -- toggle viewer viewed state
			},
			file_panel = {
				next_entry = "Zj", -- move to next changed file
				prev_entry = "Zk", -- move to previous changed file
				select_entry = "Z<cr>", -- show selected changed file diffs
				refresh_files = "ZR", -- refresh changed files panel
				focus_files = "Z<leader>e", -- move focus to changed file panel
				toggle_files = "Z<leader>b", -- hide/show changed files panel
				select_next_entry = "Z]q", -- move to previous changed file
				select_prev_entry = "Z[q", -- move to next changed file
				close_review_tab = "Z<C-c>", -- close review tab
				toggle_viewed = "Z<leader><space>", -- toggle viewer viewed state
			},
		},
	})
end

return M
